### ISSUE TITLE
Crystalball supports only circular DS9 region files 

### ISSUE THREAD

**Issue by KshitijT** [paoloserra/crystalball#17]
I am using Crystalball and running into this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/crystalball", line 7, in <module>
    pkg.main([a for a in sys.argv[1:]])
  File "/usr/local/lib/python2.7/dist-packages/Crystalball/main.py", line 10, in main
    predictor.predict( p.parse_args() )
  File "/usr/local/lib/python2.7/dist-packages/Crystalball/crystalball.py", line 172, in predict
    num=args.num_sources or None)
  File "/usr/local/lib/python2.7/dist-packages/Crystalball/wsclean.py", line 88, in import_from_wsclean
    raise ValueError('Only circular DS( regions supported for now')
ValueError: Only circular DS( regions supported for now
```
While I am happy to make Circular region files, it might not be the best thing to do since radio sources are not guaranteed to be circular.

**Comment by paoloserra** [comment]
pinging @o-smirnov

**Comment by o-smirnov** [comment]
Yeah sorry, this is a limitation that needs to be either fixed or documented in the help clearly. 

It should have been very simple. I just read the regions files with the ``pyregions`` package (here: https://github.com/paoloserra/crystalball/blob/master/Crystalball/crystalball.py#L156), then I should be able to use the ``region.contains()`` method to determine whether each component is inside a region. However, ``contains()`` was broken as of March (see comment here: https://github.com/paoloserra/crystalball/blob/master/Crystalball/wsclean.py#L82). So as a workaround, I kludged in a check to look at region centres, and pick components within a radius of that.

I see ``pyregion`` is under active development so perhaps the earlier bug has been fixed. @KshitijT if you want to help yourself, feel free to give it a try, if it works, the code should be dead simple. And if it doesn't, we just revert to my kludge and add a note to the help. Or adopt @bennahugo's solution for determining regions...

**Comment by KshitijT** [comment]
@o-smirnov , I'll give it a shot.

> Or adopt @bennahugo's solution for determining regions...


Do you mean CatDagger? I am not skilled enough to catch make regions with it which are **not** for dE calibration tagging..

**Comment by o-smirnov** [comment]
He had some fancy code for determining whether a source is inside a region. But that's bringing tactical nuclear warheads to a pillow fight in this case. 

It **should** be as easy as ``include = any([reg.contains(coord) for reg in include_regions])``, if contains() works properly now.

**Comment by o-smirnov** [comment]
The region list is read [here](https://github.com/paoloserra/crystalball/blob/master/Crystalball/crystalball.py#L156), you shouldn't need to mess with that, it should read any ds9 file. 

It's then passed (as a list called ``include_regions``) to ``import_from_wsclean``. So all you need to do is to fix the condiitonal here: https://github.com/paoloserra/crystalball/blob/master/Crystalball/wsclean.py#L80

**Comment by bennahugo** [comment]
Fancy code... hehe its called a dot product :) Anyway my solution will work
for arbitrary shaped convex hulls

**Comment by bennahugo** [comment]
https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler/geometry.py#L333

**Comment by ktrehaeven** [comment]
Hi. Can I just ask if support for non-circular regions is actually available?
